package fr.emse.ewall.model;

import java.time.LocalDateTime;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;

/**
 * QRcode are linked with a {@link Category}. The QRCodes are generated by admin users on the category screen
 *
 * @author Dev-Mind <guillaume@dev-mind.fr>
 * @since 07/12/15.
 */
@Entity
public class QrCode {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @JsonView({FlatView.class, CompleteView.class})
    private Long id;

    @ManyToOne
    @JsonIgnore
    public Category category;

    @ManyToOne
    @JsonView({FlatView.class, CompleteView.class})
    Production production;

    @org.hibernate.annotations.Type(type = "org.jadira.usertype.dateandtime.threeten.PersistentLocalDateTime")
    @JsonView(CompleteView.class)
    private LocalDateTime generatedAt = LocalDateTime.now();

    /**
     * A QRcode help to open an URL
     */
    @NotNull
    @JsonView(FlatView.class)
    private String url;

    @Lob
    @JsonView(FlatView.class)
    private String svgPath;

    /**
     * If true the QR Code is linked to the category to navigate to it.
     * If false the QR code is used to paint a big one and we define coordinates x and y axis
     */
    private Boolean big;

    /**
     * X axis value for a QRCode included in a big one
     */
    private int x;

    /**
     * Y axis value for a QRCode included in a big one
     */
    private int y;

    /**
     * Dimension depends on the QRCode version
     */
    private int dimension;

    public Long getId() {
        return id;
    }

    public QrCode setId(Long id) {
        this.id = id;
        return this;
    }

    public Category getCategory() {
        return category;
    }

    public QrCode setCategory(Category category) {
        this.category = category;
        return this;
    }

    public Production getProduction() {
        return production;
    }

    public QrCode setProduction(Production production) {
        this.production = production;
        return this;
    }

    public LocalDateTime getGeneratedAt() {
        return generatedAt;
    }

    public QrCode setGeneratedAt(LocalDateTime generatedAt) {
        this.generatedAt = generatedAt;
        return this;
    }

    public String getUrl() {
        return url;
    }

    public QrCode setUrl(String url) {
        this.url = url;
        return this;
    }

    public Boolean getBig() {
        return big;
    }

    public QrCode setBig(Boolean big) {
        this.big = big;
        return this;
    }

    public int getX() {
        return x;
    }

    public QrCode setX(int x) {
        this.x = x;
        return this;
    }

    public int getY() {
        return y;
    }

    public QrCode setY(int y) {
        this.y = y;
        return this;
    }

    public String getSvgPath() {
        return svgPath;
    }

    public QrCode setSvgPath(String svgPath) {
        this.svgPath = svgPath;
        return this;
    }

    public int getDimension() {
        return dimension;
    }

    public QrCode setDimension(int dimension) {
        this.dimension = dimension;
        return this;
    }
}
