package fr.emse.numericwall.model;

import java.time.LocalDateTime;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

/**
 * QRcode are linked with a {@link Category}. The QRCodes are generated by admin users on the category screen
 *
 * @author Dev-Mind <guillaume@dev-mind.fr>
 * @since 07/12/15.
 */
@Entity
public class NwQrCode {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ManyToOne
    public Category category;

    @ManyToOne
    Work work;

    @org.hibernate.annotations.Type(type = "org.jadira.usertype.dateandtime.threeten.PersistentLocalDateTime")
    private LocalDateTime generatedAt = LocalDateTime.now();

    /**
     * A QRcode help to open an URL
     */
    @NotNull
    private String url;

    /**
     * If true the QR Code is linked to the category to navigate to it.
     * If false the QR code is used to paint a big one and we define coordinates x and y axis
     */
    private Boolean big;

    /**
     * X axis value for a QRCode included in a big one
     */
    private int x;

    /**
     * Y axis value for a QRCode included in a big one
     */
    private int y;

    public Long getId() {
        return id;
    }

    public NwQrCode setId(Long id) {
        this.id = id;
        return this;
    }

    public Category getCategory() {
        return category;
    }

    public NwQrCode setCategory(Category category) {
        this.category = category;
        return this;
    }

    public Work getWork() {
        return work;
    }

    public NwQrCode setWork(Work work) {
        this.work = work;
        return this;
    }

    public LocalDateTime getGeneratedAt() {
        return generatedAt;
    }

    public NwQrCode setGeneratedAt(LocalDateTime generatedAt) {
        this.generatedAt = generatedAt;
        return this;
    }

    public String getUrl() {
        return url;
    }

    public NwQrCode setUrl(String url) {
        this.url = url;
        return this;
    }

    public Boolean getBig() {
        return big;
    }

    public NwQrCode setBig(Boolean big) {
        this.big = big;
        return this;
    }

    public int getX() {
        return x;
    }

    public NwQrCode setX(int x) {
        this.x = x;
        return this;
    }

    public int getY() {
        return y;
    }

    public NwQrCode setY(int y) {
        this.y = y;
        return this;
    }
}
